### ISSUE TITLE
Cannot edit own test

### ISSUE THREAD

**Issue by madskonradsen** [jsperf/jsperf.com#153]
It doesn't seem possible to edit my own tests as it just creates a new page instead of updating as `request.yar.get('own')` never gets set. It might just be something with my setup.

**Comment by maxbeatty** [comment]
confirmed `yar.set('own')` isn't happening outside of unit tests. wondering if we should instead persist something from GH auth to find "own"

**Comment by madskonradsen** [comment]
But we don't store anything unique about the user when they create a page, how would we know, across browser sessions, that they did in fact create a particular page? Should the pages-entity be  extended with another column containing something from GH auth, and how do can we avoid people tampering with the data in the callback from Github?

**Comment by maxbeatty** [comment]
correct, we would need to alter the mysql schema to store something unique from [their profile](https://github.com/jsperf/jsperf.com/blob/9d84caedebccada956454f4db0461b83a345df5c/server/web/auth/github.js#L9)

> how can we avoid people tampering with the data in the callback from Github?

OAuth is trustworthy enough for me

**Comment by madskonradsen** [comment]
Oh... It's using OAuth... No problem then. Maybe i should have verified how the integration worked before blabbering ;)

**Comment by madskonradsen** [comment]
Just leaving a link to the bulkUpdate-edit-issue: https://github.com/jsperf/jsperf.com/pull/143#discussion_r71999367

**Comment by mathiasbynens** [comment]
This is needed for #232 as well.

**Comment by JonasNo** [comment]
I do not understand why this is so hard to fix. It worked before. Why not use the git repo history to track down what changes broke the site?
I would but I don't know how to setup this, make it run and ability to debug. I know Javascript but not the other stuff (server/client). Yes I've read the instructions but since I do not know how this will affect my machine I'm worried about accidentally opening up my machine to internet.
Is this project abandoned?

**Comment by madskonradsen** [comment]
No, this project is not abandoned. In case you havn't noticed is this an open-source project. People don't get paid. People do this because they think it's fun. Pay people to fix it, wait, or fix it yourself.

**Comment by JonasNo** [comment]
You did not understand the question. When an open source project is considered abandoned the original author(s) have lost interest in it. Basically drops the ball and walks away.

> In case you havn't noticed is this an open-source project. People don't get paid. People do this because they think it's fun. Pay people to fix it, wait, or fix it yourself.

What's with that condescending attitude? Such a waste of time. So unnecessary and uncalled for. Learn to control your damage and keep it to yourself. Talk to a friend or a professional or both, please. There are even forums for it. This site is however not the place.

**Comment by madskonradsen** [comment]
"I do not understand why this is so hard to fix." is what's up.

**Comment by mathiasbynens** [comment]
> I do not understand why this is so hard to fix. It worked before. Why not use the git repo history to track down what changes broke the site?

The project has been rewritten from scratch in Node.js. The old version was PHP-based. There is no change that broke this — it just hasn’t been implemented yet in the new version. If you had taken your own advice and “used the git repo history” you would’ve known this already.

**Comment by jdalton** [comment]
> "I do not understand why this is so hard to fix." is what's up.

A PR is worth a thousand pings.

**Comment by LeZuse** [comment]
I just made a very quick dirty fix for that at https://github.com/LeZuse/jsperf.com/pull/1

**Comment by JonasNo** [comment]
jdalton
"A PR is worth more than a thousand pings."
PR, is that Public Repo in this context?

mathiasbynens
Good to see at least someone takes time to clear things up. Thank you. I got my answer. :+1:

"if you had taken your own advice and “used the git repo history” you would’ve known this already."

I got the impression the new site wasn't up yet and that there were problems with the old site due to some commit. So reverting the commit would fix the problem hence why I said "I do not understand why this is so hard to fix".
Thought that was clear in my first comment. Guess other people didn't understand too. So should I start mocking too? But I will not because I'm above that :tophat:  :innocent: and :point_up: also this isn't a place for that as I also pointed out. 

Guess people don't read. Just jumps on the bandwagon of quotations and useless comments.  :sheep: More waste of time.
But it's nice to be quoted. :smile: Do continue.  :trollface:

Cheers. :beer: :beers: :wine_glass: :v: :wave:

**Comment by madskonradsen** [comment]
Nice @LeZuse what about auto-filling the e-mail field? That way we would cases where people misspelled their e-mail address and thereby lost ownership over their testcase. The e-mail field could also be removed from the page so that it's just used for authentication. I guess most people would use the comment feature to discuss stuff anyway. What do you think @mathiasbynens ? :)

**Comment by mathiasbynens** [comment]
The email field was there because we use it to display avatars (through Gravatar). If we already get access to the email address through GitHub OAuth then I agree we don’t need the field anymore — we can store it implicitly. 👍

**Comment by maxbeatty** [comment]
created #312 to track progress on using GitHub profile info

**Comment by maxbeatty** [comment]
should now be able to edit your own tests thanks to #325
