### ISSUE TITLE
Jsperv.com (note typo) web site?

### ISSUE THREAD

**Issue by BurtHarris** [jsperf/jsperf.com#191]
I tried to get to the jsper**f**.com web site today, but somehow landed on jsper**v**.com.   I authenticated using GitHub.   Now that I see I didn't get the site I originally expected, I'm concerned if this has security implications.   

Any information about this site?  Is it a well-intended clone or some sort of bad intent?

**Comment by chet-manley** [comment]
![image](https://cloud.githubusercontent.com/assets/6780085/18687791/4d9eb460-7f47-11e6-800d-5045d9dd7ff4.png)

I haven't been able to reach jsperf.com in over a year. This screencap is from today.

**Comment by maxbeatty** [comment]
Sorry for the confusion. You've stumbled upon our continuously deployed instance of this repository with old data from the original jsPerf site. It has some bugs which is why jsper**f**.com (f) has not been switched over. You can help by creating Issues here with steps to reproduce issues you encounter.

jsper**v**.com (v) is owned by @jsperf. You can verify the owner of the OAuth application by going to ["Authorized applications" in your GitHub settings](https://github.com/settings/applications?o=used-desc), clicking on "jsPerf", and seeing the http://jsperv.com domain listed.

**Comment by BurtHarris** [comment]
thanks for the explanation max
