### ISSUE TITLE
ui.js: Browserscope integration seems broken in Chrome/Opera

### ISSUE THREAD

**Issue by mathiasbynens** [jsperf/jsperf.com#235]
E.g. https://jsperf.com/slugs#results

No results show up in Chrome/Opera:

![](https://cloud.githubusercontent.com/assets/81942/19508660/b4418e82-95da-11e6-9855-b79de230f4da.png)

This seems to be a client-side issue, although no JS errors get logged.

@jdalton, any ideas?

**Comment by mscdex** [comment]
I saw this too, one error I see in the browser console is that underscore is being loaded over http and jsperf is served over https. Fixing that is not a matter of switching to https for the underscore script tag because underscorejs.org is served by github and so you'll get an SSL error because the CN doesn't match.

I think the only fix for that is to get underscore from somewhere else that uses https.

**Comment by jdalton** [comment]
Related to https://code.google.com/archive/p/browserscope/issues/357.

**Comment by mathiasbynens** [comment]
@ Brian who commented here but removed the comment: you seem to be talking about a test case that triggers mixed content errors. That is an issue with that specific test case, not jsPerf itself. (If jsPerf had this problem you’d see a warning in the console on _any_ test case.)

@jdalton

> https://code.google.com/archive/p/browserscope/issues/357

That has been resolved for a while now — Browserscope supports HTTPS nowadays. (I guess Brian’s comment threw you off.)

Any idea what’s causing the Browserscope issues?

**Comment by demoneaux** [comment]
This seems to be a Chrome specific issue. Loading on Edge works fine. Based on a quick look, it seems that [`ui.browserscope.container` is not yet defined when accessed](https://github.com/bestiejs/benchmark.js/blob/c51e721c40f31037c9d8a142eff97fb884022ab3/plugin/ui.browserscope.js#L1048), even though the iframe is closed. Shifting [these two lines](https://github.com/bestiejs/benchmark.js/blob/c51e721c40f31037c9d8a142eff97fb884022ab3/plugin/ui.browserscope.js#L1047-L1051) into the [timeout here](https://github.com/jsperf/jsperf.com/blob/20e0d191c4a25c2252f5a7646ab9098b513a4259/gulpfile.js#L78) should be able to fix this problem. This issue is probably due to changes to iframe rendering in Chrome, since this used to work in the past.

**Comment by mathiasbynens** [comment]
@demoneaux Nice find! Wanna submit a PR for that workaround?

**Comment by demoneaux** [comment]
Any update on jsPerf’s end?

**Comment by mathiasbynens** [comment]
@jdalton Mind bumping the Benchmark.js version number?

**Comment by demoneaux** [comment]
Looking at it again, this still seems to be broken. Not very sure what to do next...

**Comment by maxbeatty** [comment]
Related: after tests are run, the form post to browserscope fails because of mixed content. Is [this GitHub repo](https://github.com/elsigh/browserscope/blob/646e3f7c941b6cdebdb3d76d4800980fd6e99da4/templates/user_test_beacon.js#L100) the source to fix?

**Comment by mathiasbynens** [comment]
@maxbeatty Looks like it — we don’t force `http://` for Browserscope anywhere in our code (not even in our docs after merging #321).

I’ve submitted https://github.com/elsigh/browserscope/pull/5.
