### ISSUE TITLE
When editing, no option to add a code snippet

### ISSUE THREAD

**Issue by jwdunn1** [jsperf/jsperf.com#247]
When editing an existing test, there does not appear to be an interface element to "add" a new code snippet like there is when creating a new test.

Expected behavior: when editing a test such as //jsperf.com/transpose-2d-array/5/edit
there should be a button at the bottom of the code snippets section to "Add code snippet".

PS, I am on Chrome 54 Win 10.

**Comment by FredyC** [comment]
I confirm this is happening to me as well. On top of that if I actually edit preparation code and want to save it, I am getting `Not all tests inserted` error message after confirming captcha and test case is not saved at all.

**Comment by FredyC** [comment]
Actually there is even more to it. It creates new revision of the test case, but completely wiped out from all snippets

https://jsperf.com/rest-params-vs-arguments-complex/1/edit
https://jsperf.com/rest-params-vs-arguments-complex/2/edit

**Comment by mudcatthefish** [comment]
I am seeing the same issues as jwdunn1 and FreddyC in both Firefox and Chrome.

**Comment by OvermindDL1** [comment]
Same issue a month later too.

**Comment by FredyC** [comment]
Just little tip as development of this is kinda stale ... https://esbench.com/

**Comment by maxbeatty** [comment]
If you're in a position to sponsor jsPerf, please see #291

**Comment by willthemoor** [comment]
Wish I was in a position to sponsor. 

Everyone on the team is probably already aware at this point but in case it helps... it looks like that limit of two snippets is also evident on new tests. I can't save a test with more than two snippets anyway. Well, I did once a couple of days ago but there was a typo! And haven't been able to since. When editing it or trying to make a new version from scratch I get either `Please review required fields and save again.` or `Not all tests inserted`. 

If I make a test with only two snippets, it will save. If you look through https://jsperf.com/browse you can see that most new tests that actually have tests (most have 0) are 2 snippets long though a few bigger ones seem to get through somehow!

**Comment by FredyC** [comment]
@willthemoor What you don't like about https://esbench.com/ ? It's fully fledged alternative that actually works.

**Comment by willthemoor** [comment]
@FredyC Not sure that matters, does it? Not complaining. Just reporting what I saw to the jsperf team in case it's helpful. I'm sure they'd prefer a donation or a pull request but can't really do either so I report.
