### ISSUE TITLE
Spam samples

### ISSUE THREAD

**Issue by hubdotcom** [jsperf/jsperf.com#28]
Could you provide some samples of the spam so we can help in building a better filter to protect against these?

**Comment by Ladestatus** [comment]
https://www.google.de/search?q=js+perf+key&ie=utf-8&oe=utf-8&gws_rd=cr&ei=8MyPVZPMBIPiywOt0IWwDw#safe=off&q=jsperf+warez

**Comment by hubdotcom** [comment]
Looks like this was automated? Several options for stopping this:

1. Add a field that is populated by javascript will stop all but the smartest bots
http://davidwalsh.name/wordpress-comment-spam

2. Add a field that should remain blank and is hidden via css - bots may fill this in
<input type='text' name='name'>

3. Check entries via akismet or another 3rd party service
https://akismet.com/development/api/#detailed-docs 

I would be happy to implement 1 + 2 to stop this spam

**Comment by mathiasbynens** [comment]
@hubdotcom 

1. has been implemented in jsPerf from the start. Didn’t help in this case, as the spammer seemed to specifically target jsPerf.
2. Wouldn’t work, since the spammer specifically targets jsPerf and would let their script not fill in the field.
3. Was implemented in jsPerf near the end, along with Cloudflare’s basic spam protection. Most spam still got through and many legitimate test cases were flagged as spam, even after training Akismet for a few weeks.

The spammer specifically targeted jsPerf and tweaked their script whenever the spam filter started catching up. Here’s just a small spam sample:

```
jsperf-spam-entries-sample.sql.tar.gz 634.1 MB
https://mega.co.nz/#!KsYl0LRB!9JjIT0jK01ezSoRGbiK6GaQHee7TgoIUWwtdQ6x6qyw
```

Given this sample it’s trivial to implement protection against these specific entries. But that’s the problem: once this protection is in place, the spammer just moves on to another entry format. It’s a perpetual cat and mouse game.

I’m confident #19 will fix the issue.

**Comment by hubdotcom** [comment]
This is true and perhaps there is an easier way to address to get the site back online ASAP.

How about populating a field via javascript based on a server provided nonce (this way it would be impossible to bypass without having the browser js enabled).

The step up from this would be captcha based limiting (which could also be implemented very quickly) with an additional option for registration to remove captcha's. reCAPTCHA has become very easy on the end user now: https://www.google.com/recaptcha/intro/index.html

IMO forced registration should be the last step to resolve
