### ISSUE TITLE
JSPerf still identifies Microsoft Edge as Google Chrome

### ISSUE THREAD

**Issue by BrandonLive** [jsperf/jsperf.com#46]
I saw that there was an old issue which was resolved as a duplicate of a (seemingly unrelated) platform.js bug. But even that (again, seemingly unrelated) bug has been resolved for some time. So why does JSPerf still get tripped up by the Edge UA string? This should be an easy fix.

**Comment by maxbeatty** [comment]
I believe you are referring to old issues #36 and #39. That platform.js bug was [fixed ~3 days before you opened this issue](https://github.com/bestiejs/platform.js/pull/86). JSPerf still gets tripped up because we haven't updated platform.js. We're open to [contributions](https://github.com/jsperf/jsperf.com/blob/master/CONTRIBUTING.md) if you'd be so inclined :heart_decoration:

**Comment by maxbeatty** [comment]
Also related is #33 which suggests moving away from platform.js

**Comment by aMarCruz** [comment]
@BrandonLive , you are right.
Egde user agent:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240`

**Comment by madskonradsen** [comment]
I guess this can be closed as the switch to scooter fixed it

**Comment by mathiasbynens** [comment]
Thanks, @madskonradsen. Fixed by #144.
